### PR TITLE
add script and sheets for precision plot

### PR DESCRIPTION
**Pull request by mbhall88**
Addresses #2 

Also, @leoisl, you mentioned you don't want the recall per number of samples script?

If you *do* want it though I can add it to this PR.

### CODE REVIEW

**Comment by mbhall88** [comment]
The script can just be executed with `python precision_per_sample.py` - I tested it and uploaded the plot produced with this PR

**Comment by leoisl** [comment]
I leave for @iqbal-lab to decide which script to use for `recall_per_nb_of_samples` plots. I did not test your script yet, will review this PR later (on monday). Does it also create plots for `recall_per_sample` (this is not `recall_per_nb_of_samples`, it is another plot, just like the precision one, but for recall)? If not, could we have it?

**Comment by mbhall88** [comment]
Does it also create plots for `recall_per_sample` (this is not `recall_per_nb_of_samples`, it is another plot, just like the precision one, but for recall)? If not, could we have it?

It doesn't. I have never made a plot like that?  

I guess I can make it if you want? Are we having multiple recall plots?

**Comment by iqbal-lab** [comment]
@mbhall88 you have made such a plot here:

https://github.com/leoisl/pandora1_paper_full_pipeline/issues/2#issuecomment-703331986

that's what leandro means i think

**Comment by leoisl** [comment]
Just now I realised you are using the `precision_per_ref_per_clade` csvs, I thought you were using the `precision_per_sample` csvs... `precision_per_sample` csvs would also work the same way. Just made me realise that these CSVs are actually very similar to each other. `precision_per_sample` has information about which filters were used though... Might remove the `precision_per_sample` and `recall_per_sample` csvs. The recall counterpart of this plot should thus be made from the `recall_per_ref_per_clade` csvs

**Comment by leoisl** [comment]
I think my previous messages were thus confusing to you, as I thought you were using another input, sorry about that

**Pull request merged**
